info:
  name: Buscar configuração
  type: http
  seq: 1

http:
  method: GET
  url: "{{url}}/setup/preferences"
  headers:
    - name: Authorization
      value: Bearer {{access_token}}
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
